spring:
  application:
    name: msnotification
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      authentication-database: admin
      database: notification
      port: 27017
      host: localhost
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq: 
  queues:
    notify: notify  