spring:
  application:
    name: mstask
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      authentication-database: admin
      database: task
      port: 27016
      host: localhost
          
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq: 
  queues:
    notify: notify 
